version: '3.9'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '${PORT}:3000'
    volumes:
      - app_data:/app
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - '${DB_HOST_PORT}:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/db/migrations/:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  app_data:
  db_data:
