version: '3.9'
services:
  app:
    container_name: app
    build: .
    ports:
      - '${PORT}:3000'
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
